### PR TITLE
#2347 : Add django_mailbox

### PR DESCRIPTION
**Pull request by khchine5**

### CODE REVIEW

**Comment by lsaffre** [comment]
@Hamza, why did you add this? django-mailbox is required only by applications that use lino_xl.lib.mailbox. Lino should not depend on it. Even lino_xl shouldn't, because many applications  don't need django-mailbox. E.g. Lino Tera does not use lino_xl.lib.mailbox, so it would be disturbing if django-mailbox gets installed on a Lino Tera site.

**Comment by khchine5** [comment]
The test suits fails because the django-mailbox is not installed. I will changed it to the the book and on the test section.

**Comment by hamza** [comment]
You guys have tagged the wrong person FYI

**Comment by lsaffre** [comment]
Oops I see. Thanks @hamza for mentioning.

**Pull request merged**
